var COLOR_BASELINE = '#2ecc71';
var COLOR_BASELINE_SELECTED = '#e74c3c';
var LINE_WIDTH_BASELINE = 3;

var COLOR_BOUNDINGBOX = '#3498db';
var COLOR_BOUNDINGBOX_SELECTED = '#e74c3c';
var COLOR_BOUNDINGBOX_LABELED = '#2ecc71';
var COLOR_BOUNDINGBOX_HOVER = '#f2ca27';
var ALPHA_BOUNDINGBOX = 0.4;

var COLOR_PREVIEW_LINES = '#ff0000';
var COLOR_PREVIEW_BASELINE = '#2ecc71';